Altinn/altinn-support-dashboard

frontend/altinn-support-dashboard.client/src/App.tsx, frontend/altinn-support-dashboard.client/src/components/MainContent.tsx
=> 67 implementering av underenhetsk i backend

frontend/altinn-support-dashboard.client/.vite/deps_temp_167ae938/package.json, frontend/altinn-support-dashboard.client/.vite/deps_temp_796f6a3f/package.json, frontend/altinn-support-dashboard.client/src/app/App.css, frontend/altinn-support-dashboard.client/src/app/App.tsx, frontend/altinn-support-dashboard.client/src/components/MainContent/MainContentComponent.tsx, frontend/altinn-support-dashboard.client/src/components/Sidebar/SidebarComponent.tsx
=> 77 implementere frontend error visning

frontend/altinn-support-dashboard.client/src/app/App.tsx, frontend/altinn-support-dashboard.client/src/components/MainContent/MainContentComponent.tsx
=> Fixed suborg handling, to use main org to view er-roller

frontend/altinn-support-dashboard.client/src/app/App.css, frontend/altinn-support-dashboard.client/src/app/App.tsx, frontend/altinn-support-dashboard.client/src/components/MainContent/MainContentComponent.tsx, frontend/altinn-support-dashboard.client/src/components/TopSearchBar/TopSearchBarComponent.tsx
=> 86 endringer i visning

backend/src/altinn-support-dashboard.backend/Controllers/AltinnController.cs, frontend/altinn-support-dashboard.client/src/app/App.css, frontend/altinn-support-dashboard.client/src/app/App.tsx, frontend/altinn-support-dashboard.client/src/components/Sidebar/SidebarComponent.tsx
=> added functonality to enviromentselector in sidebar

frontend/altinn-support-dashboard.client/package-lock.json, frontend/altinn-support-dashboard.client/package.json
=> package update jest

frontend/altinn-support-dashboard.client/package-lock.json, frontend/altinn-support-dashboard.client/package.json, frontend/altinn-support-dashboard.client/src/components/MainContent/MainContentComponent.tsx, frontend/altinn-support-dashboard.client/tsconfig.app.json, package-lock.json, package.json
=> Jestupdate 2.0

frontend/altinn-support-dashboard.client/altinn-support-dashboard.esproj, frontend/altinn-support-dashboard.client/package-lock.json, frontend/altinn-support-dashboard.client/package.json, frontend/altinn-support-dashboard.client/src/components/MainContent/MainContentComponent.tsx, frontend/altinn-support-dashboard.client/tsconfig.app.json, frontend/altinn-support-dashboard.client/tsconfig.json, frontend/altinn-support-dashboard.client/tsconfig.node.json, package-lock.json, package.json
=> Jestupdate

frontend/altinn-support-dashboard.client/src/app/App.tsx
=> changed from localhost to window.location.origin

backend/src/altinn-support-dashboard.backend/Clients/DataBrregClient.cs, backend/src/altinn-support-dashboard.backend/Controllers/DataBrregController.cs, backend/src/altinn-support-dashboard.backend/Services/DataBrregService.cs, backend/src/altinn-support-dashboard.backend/Services/Interfaces/IDataBrregService.cs, backend/src/altinn-support-dashboard.backend/appsettings.json
=> added new brregclient config with dynamic swithc

backend/src/altinn-support-dashboard.backend/Clients/DataBrregClient.cs, backend/src/altinn-support-dashboard.backend/Controllers/DataBrregController.cs, backend/src/altinn-support-dashboard.backend/Services/DataBrregService.cs, backend/src/altinn-support-dashboard.backend/Services/Interfaces/IDataBrregService.cs, backend/src/altinn-support-dashboard.backend/appsettings.json, backend/test/altinn-support-dashboard.backend.Tests/Controllers/DataBrregControllerTests.cs
=> added working tests

backend/src/altinn-support-dashboard.backend/Program.cs
=> added brregconfigure to program

backend/src/altinn-support-dashboard.backend/Controllers/DataBrregController.cs
=> removed authorize from brregapi since opendata

backend/src/altinn-support-dashboard.backend/Controllers/AltinnController.cs, backend/src/altinn-support-dashboard.backend/Controllers/DataBrregController.cs, frontend/altinn-support-dashboard.client/src/app/App.tsx, frontend/altinn-support-dashboard.client/src/components/MainContent/MainContentComponent.tsx
=> changed controller endpoint,and frontend errormessage

frontend/altinn-support-dashboard.client/src/components/Sidebar/SidebarComponent.tsx
=> changed "emails" to "preferred_username"

backend/src/altinn-support-dashboard.backend/Models/OfficialContact.cs, backend/src/altinn-support-dashboard.backend/Models/OrganizationModel.cs, backend/src/altinn-support-dashboard.backend/Models/PersonalContact.cs
=> made datetime nullableablable

backend/src/altinn-support-dashboard.backend/wwwroot/dist/index.html, frontend/altinn-support-dashboard.client/src/app/App.tsx
=> removed port, added newest build

frontend/altinn-support-dashboard.client/src/components/SettingsContent/SettingsContentComponent.tsx
=> fixed version number

frontend/altinn-support-dashboard.client/src/components/MainContent/MainContentComponent.tsx, frontend/altinn-support-dashboard.client/src/components/SettingsContent/SettingsContentComponent.tsx, frontend/altinn-support-dashboard.client/src/hooks/hooks.ts, frontend/altinn-support-dashboard.client/src/models/models.ts, frontend/altinn-support-dashboard.client/src/utils/utils.ts
=> Status and text handling

frontend/altinn-support-dashboard.client/src/app/App.tsx, frontend/altinn-support-dashboard.client/src/components/MainContent/MainContentComponent.tsx, frontend/altinn-support-dashboard.client/src/components/ManualRoleSearch/ManualRoleSearchComponent.tsx, frontend/altinn-support-dashboard.client/src/components/SettingsContent/SettingsContentComponent.tsx, frontend/altinn-support-dashboard.client/src/components/Sidebar/SidebarComponent.tsx, frontend/altinn-support-dashboard.client/src/components/TopSearchBar/TopSearchBarComponent.tsx, frontend/altinn-support-dashboard.client/src/hooks/hooks.ts, frontend/altinn-support-dashboard.client/src/models/models.ts, frontend/altinn-support-dashboard.client/src/utils/utils.ts
Also cleaned entire code. 
- #{issue number}
=> Added a localDev const checking for enviroment.

backend/src/altinn-support-dashboard.backend/Controllers/GiteaController.cs, backend/src/altinn-support-dashboard.backend/Models/Gitea/CreateOrganizationRequestModel.cs, backend/src/altinn-support-dashboard.backend/Models/Gitea/PatTokenRequestModel.cs, backend/src/altinn-support-dashboard.backend/Models/Gitea/RepositoryRequestModel.cs, backend/src/altinn-support-dashboard.backend/Models/Gitea/TeamRequestModel.cs, backend/test/altinn-support-dashboard.backend.Tests/Controllers/GiteaApiControllerTests.cs, frontend/altinn-support-dashboard.client/src/components/GiteaOrganization/GiteaComponent.tsx
=> Recovery gitea api

backend/src/altinn-support-dashboard.backend/Clients/DataBrregClient.cs
=> fix: added size 10000 to request url for subunit.

frontend/altinn-support-dashboard.client/src/components/MainContent/MainContentComponent.tsx
=> fix: view for roles in styre

frontend/altinn-support-dashboard.client/src/components/ManualRoleSearch/ManualRoleSearchComponent.tsx
=> (rollback to branch)

backend/src/altinn-support-dashboard.backend/appsettings.json, frontend/altinn-support-dashboard.client/public/version.json, frontend/altinn-support-dashboard.client/src/app/App.tsx, frontend/altinn-support-dashboard.client/src/components/SettingsContent/SettingsContentComponent.tsx, frontend/altinn-support-dashboard.client/src/components/SettingsContent/utils/versionUtils.ts, frontend/altinn-support-dashboard.client/src/components/VersionDialog/VersionDialog.tsx, frontend/altinn-support-dashboard.client/src/hooks/useVersionCheck.ts, tree.md
=> feat: added new version system, with dialog for users

frontend/altinn-support-dashboard.client/src/components/TopSearchBar/TopSearchBarComponent.tsx, frontend/altinn-support-dashboard.client/src/components/TopSearchBar/TopSearchBarTextField.tsx, frontend/altinn-support-dashboard.client/src/pages/DashboardPage.tsx
- Moved the searchbar component into it's own file and cleaned up the TopSearchBarComponent.tsx file
=> 193 Refactor TopSearchBarComponent

frontend/altinn-support-dashboard.client/src/app/App.tsx, frontend/altinn-support-dashboard.client/src/hooks/hooks.ts, frontend/altinn-support-dashboard.client/src/pages/ManualRoleSearchPage.tsx, frontend/altinn-support-dashboard.client/src/utils/api.ts
Removde unused hooks which were outdated. Also merged the two pai calls which fetched the same information into one.
=> 245 fjern useenvironment og usedarkmode

frontend/altinn-support-dashboard.client/src/components/Dashboard/components/ERRolesTable.tsx, frontend/altinn-support-dashboard.client/src/components/Dashboard/components/contacts/ContactInfoCell.tsx, frontend/altinn-support-dashboard.client/src/components/Dashboard/components/contacts/ContactsTable.tsx, frontend/altinn-support-dashboard.client/src/components/Dashboard/models/mainContentTypes.ts, frontend/altinn-support-dashboard.client/src/components/Dashboard/styles/ContactInfoCell.module.css, frontend/altinn-support-dashboard.client/src/components/Dashboard/styles/ContactsTable.module.css, frontend/altinn-support-dashboard.client/src/components/Dashboard/utils/contactUtils.ts
This Pr migrated the contactstable over to designsystemet. Relevant styling has also been moved to css modules.
=> 255 refactor migrate contactstable to designsystemet

frontend/altinn-support-dashboard.client/src/components/Dashboard/components/contacts/ContactsSearchBar.tsx, frontend/altinn-support-dashboard.client/src/components/Dashboard/styles/ContactsSearchBar.module.css
- Migrated to Designsystemet
- Added a css module for the component
=> 254 REFACTOR: migrate contactsSearchBar to designsystemet

frontend/altinn-support-dashboard.client/src/components/Sidebar/NavItem.tsx, frontend/altinn-support-dashboard.client/src/components/Sidebar/Sidebar.tsx, frontend/altinn-support-dashboard.client/src/components/Sidebar/styles/NavItem.module.css, frontend/altinn-support-dashboard.client/src/components/Sidebar/styles/SideBarComponent.module.css
Fixed some small visual bugs with the sidebar nav items when collapsed. Also moved the minimize sidepanle button to the top of the sidepanle.
=> 286 small sidebar fix

backend/src/altinn-support-dashboard.backend/Models/RoleModel.cs, backend/src/altinn-support-dashboard.backend/Services/AltinnApiService.cs, backend/src/altinn-support-dashboard.backend/Services/Interfaces/IAltinnApiService.cs, frontend/altinn-support-dashboard.client/src/components/Dashboard/components/DetailedOrgView.tsx, frontend/altinn-support-dashboard.client/src/components/Dashboard/components/RoleDetails.tsx, frontend/altinn-support-dashboard.client/src/components/Dashboard/components/contacts/NotificationContactTable.tsx, frontend/altinn-support-dashboard.client/src/components/Dashboard/models/mainContentTypes.ts, frontend/altinn-support-dashboard.client/src/components/ManualRoleSearch/ManualRoleSearchTable.tsx, frontend/altinn-support-dashboard.client/src/components/ManualRoleSearch/models/manualRoleSearchTypes.ts, frontend/altinn-support-dashboard.client/src/hooks/hooks.ts, frontend/altinn-support-dashboard.client/src/models/models.ts, frontend/altinn-support-dashboard.client/src/utils/api.ts
Previously we did not map the data which we got from the altinn endpoints for officialcontacts or altinn roles. These has been made so the data is sendt in the correct json format to the frontend. THe frontend has been changed to be able to use the new models
=> 291 Update backend model for role and official contacts
